### PR TITLE
review castlecss-tabs

### PR DESCRIPTION
**Pull request by pascalalferink**
Hi everybody,
@amberjasmijn made a start with CastleCss Tabs. This week I expanded the code for Tabs in this branch and in the tabs-branch within CastcleCSS-docs (link: https://github.com/CastleCSS/castlecss-docs/tree/feature/castlecss-tabs)

There are three versions of Tabs:

- The default version
- Version with tab-headers justified
- Version with accordion-tabs on smaller devices (< 1024px)

Would you like to review the code? 
specifically I am wondering:

1. Do you see code-improvements?
2. Do you miss another version of tabs?

### CODE REVIEW

**Comment by dariusrosendahl** [comment]
Hey @pascalalferink ,

Nice start, a few suggestions:

- The tabs do not really look like tabs yet
- Colors perhaps something else then the blue - yellow combination?
- Use ```$radius``` on the outside of the tabs?
- Why not extend classes like tabs-header-full? Please take a look at the breadcrumbs-small class. http://castledocs.darius.dnz/breadcrumbs.html
- *Mobile accordions* make the moment is switches to an accordion configurable.

**Review by dariusrosendahl — CHANGES_REQUESTED** [review]
Hey @pascalalferink ,

Nice start, a few suggestions:

- The tabs do not really look like tabs yet
- Colors perhaps something else then the blue - yellow combination?
- Use ```$radius``` on the outside of the tabs?
- Why not extend classes like tabs-header-full? Please take a look at the breadcrumbs-small class. http://castledocs.darius.dnz/breadcrumbs.html
- *Mobile accordions* make the moment is switches to an accordion configurable.

**Comment by gbeumer** [comment]
@pascalalferink 

- I agree with @dariusrosendahl. Tabs don't really look like tabs yet. 
- Furthermore i checked the script and found it hard to read. The script is a combination of tab-accordion an regular tabs. I would prefer this in separated methods for both versions of the tabs. Maybe even separate modules is the way to go. Something like Tabs.init() and TabsAccordion.init()
- The same goes for the scss. There is no way to see in the scss file which class belogns to which type of accordion. Maybe some splitsing is better.

**Comment by pascalalferink** [comment]
Thank you all for your feedback,
The feedback has been processed into a new version of CastleCSS Tabs. I am wondering what you all think of the new version

Summary of the changes:
1. The design of the tabs has been changed, so the tabs look more like tabs.
2. The styling of the accordions is moved to a separate scss-file
3. The javascript that is necessary for the accordions is moved into separate functions.
4. Users can configure the moment the accordion switches to tabs by a css-class.
5. CastleCSS Tabs has fallbacks for exends, mixins and variables that are defined in CastleCSS Core

@CastleCSS/castlecss , Would you like to review the code again?

**Comment by gbeumer** [comment]
1. Script is much better now. Its quite readable and extendable
2. Layout of the tabs could be a little more spicy. Maybe look at some designs on the web
3. Don't use $color03 or $theme03 variables in the code. maybe you can look at castlecss-forms for an example
4. online there are some examples of tabs that have no script at all https://css-tricks.com/css3-tabs/ it is nice to take a look at that?

**Comment by pascalalferink** [comment]
Together with a designer I have made two improvements:
1: The color of an active accordion should be darker (instead of lighter)
2: users should close open accordions

**Comment by pascalalferink** [comment]
Furthermore, the layout is now more neutral.
@CastleCSS/castlecss , Can you review again?

**Review by dariusrosendahl — COMMENTED** [review]
Approved with the latest changes

**Review by dariusrosendahl — APPROVED** [review]

**Pull request merged**
